nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs

logFilters:
# See https://github.com/gatsbyjs/gatsby/issues/37242
  - text: react is listed by your project with version 18.2.0, which doesn't satisfy what gatsby (p1eae0) and other dependencies request (but they have non-overlapping ranges!). 
    level: discard
